### PR TITLE
added stamen toner map tiles

### PR DESCRIPTION
**Pull request by jdoepfert**

### CODE REVIEW

**Comment by jwass** [comment]
Thanks! Any change you can squash these so we can get rid of the `.py~` file in the history?

**Comment by jdoepfert** [comment]
should be fine now!

**Comment by habi** [comment]
Could this PR be merged?
I'd love to use the `toner` maps...

**Comment by jwass** [comment]
@habi @jdoepfert Yes! I'll see if I can get to this soon.

**Comment by ocefpaf** [comment]
> Could this PR be merged?
I'd love to use the toner maps...

You can use them already if you pass the tuple to the `tiles=` `kwarg` like:

```python
import mplleaflet
import matplotlib.pyplot as plt

fig, ax = plt.subplots()
ax.plot([-38.48, -38.48, -38.48], [-16, -13, -10], 'ro')

stamen_toner = (
    'http://a.tile.stamen.com/toner/{z}/{x}/{y}.png',
    'Map tiles by <a href="http://stamen.com">Stamen Design</a>, <a href="http://creativecommons.org/licenses/by/3.0">CC BY 3.0</a> &mdash; Map data &copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
)

mplleaflet.display(fig=fig, tiles=stamen_toner)
```

**Pull request merged**
