### PR TITLE
Added several tiles options to maptiles.py

### PR DESCRIPTION
**Pull request by mnfienen**
I added several tiling options to maptiles.py. These include:
Thunderforest Landscape, Esri Aerial, Esri National Geographic, and Stamen Watercolor.

I hope you will consider pulling them in.

Thanks!
mike

### CODE REVIEW

**Comment by mnfienen** [comment]
I meant to note, also that there are more tiles options at:
http://leaflet-extras.github.io/leaflet-providers/preview/

You probably know about that. I tried several and not all of them worked, but the ones in my pull request all tested out fine.

**Comment by mnfienen** [comment]
strange that the Travis CI failed. It doesn't seem to be something on my end.

**Comment by jwass** [comment]
Definitely nothing on your end. There's no Travis config file and I had accidentally enabled Travis for this repo so it just fails on every commit. Just disabled it so hopefully that won't happen anymore.

**Comment by jwass** [comment]
This looks great! Thanks for the additional tile sets and the link to the other providers.

One thing I'm considering is just making a separate repo with a single JSON file containing a set of free tiles. That way it can be included in other projects and we wouldn't have to keep adding them to mplleaflet.

**Comment by mnfienen** [comment]
I like the idea of the separate repo! That would be cool. I was fully hacking in getting these few new tiles set in. Some definitions include max zoom levels, etc. Not sure what it would take to implement those as well. Thanks for accepting the additions!

**Pull request merged**
