### PR TITLE
added esri_worldtopo tiles

### PR DESCRIPTION
**Pull request by smnorris**
The esri world topo maps are pretty good. They currently have better water feature coverage and building outlines in my area of interest than OSM (I should update OSM, but that is a different issue....)

### CODE REVIEW

**Comment by smnorris** [comment]
forgot to add to the tiles dict, fixing

**Comment by smnorris** [comment]
dang, looks like the fix was automatically added to the PR, reopening

**Comment by smnorris** [comment]
Fixed. I should have tested - sorry and thanks for the handy module.

I'd love to change the multi-line list of credits to a link like this... but I'm not sure if that would be appropriate.

`<a href="http://services.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer">&copy; Esri</a>`

screenshot 2015-10-17 11 37 30

**Comment by jwass** [comment]
Thanks!
Yeah, the attribution here is quite long, but I agree that we should leave it since we can't be sure that shortening it would be acceptable.

**Pull request merged**
