### PR TITLE
Adding authors file.

### PR DESCRIPTION
**Pull request by jwass**
@BibMartin @mariusvniekerk @michelleful @ocefpaf @mnfienen 
I'd like to put this on master soon. Please let me know if there are any objections or corrections that need to be made.

### CODE REVIEW

**Comment by michelleful** [comment]
It's Michelle Fullwood with two L's in each name. Thanks!

**Comment by jwass** [comment]
@michelleful I should know better! Thanks, fixed.

**Comment by mariusvniekerk** [comment]
Looks fine for mine

**Comment by mnfienen** [comment]
Thanks! Mnfienen is Mike Fienen. 

Cheers
Mike

**Comment by jwass** [comment]
@mnfienen Awesome. Fixed, thanks!

**Comment by BibMartin** [comment]
It's also ok for me. Thanks

**Comment by ocefpaf** [comment]
Looks fine.  Thanks!

PS: If you want the full name it is `Filipe Fernandes`

**Comment by jwass** [comment]
Squashed and merged. Thanks, everyone.

**Pull request merged**
